language: bash
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libevent-dev
      - libncurses-dev
      - expect
env:
  - TMUX_VERSION=master
  - TMUX_VERSION=2.4
  - TMUX_VERSION=2.3
  - TMUX_VERSION=2.2
  - TMUX_VERSION=2.1
  - TMUX_VERSION=2.0
  - TMUX_VERSION=1.9a
matrix:
  allow_failures:
  - env: TMUX_VERSION=master

before_script:
  # clone and install bats
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin
  # clone and build tmux version $TMUX_VERSION
  - git clone https://github.com/tmux/tmux.git tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure --prefix=$HOME/tmux && make && make install
  - export PATH=$HOME/tmux/bin:$PATH
  - cd ..
  - tmux -V

script:
  - bats test/unit-tests/*.bats
  - bash test/integration-tests/run_integration_tests.sh
