dist: trusty
sudo: false
addons:
  apt:
    packages:
    - tmux
    - expect

before_script:
  - git clone https://github.com/sstephenson/bats.git /tmp/bats
  - mkdir -p /tmp/local
  - bash /tmp/bats/install.sh /tmp/local
  - export PATH=$PATH:/tmp/local/bin
script:
  - bats test/unit-tests/*.bats
  - bash test/integration-tests/run_integration_tests.sh
