#!/usr/bin/env bash
#
# tmux-gitbar: Git in tmux status bar
#
# Created by Aurélien Rainone
# github.com/aurelien-rainone/tmux-gitbar

main () {
  local SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  source "${SCRIPT_DIR}/lib/tmux-gitbar.sh"

  find_readlink
  load_config
  update_gitbar
}

main

